#!/usr/bin/env bash

control_pipe="/tmp/jukebox-pipe"
rm "$control_pipe"; mkfifo "$control_pipe"

function play {
    killall mplayer >/dev/null 2>&1
    nohup mplayer -slave $1 -input file="$control_pipe" >/dev/null 2>&1 &
}

while true; do
    read -p "Warte auf Tag... " id

    if [[ "$id" == "0001212865" ]]; then
        play "song1.ogg"
    fi

    if [[ "$id" == "0004633422" ]]; then
        play "song2.ogg"
    fi

    # Pause
    if [[ "$id" == "0001495377" ]]; then
        echo "pause" > "$control_pipe"
    fi

    # 10 Sekunden Sprung
    if [[ "$id" == "0004622843" ]]; then
        echo "seek 10 0" > "$control_pipe"
    fi

    sleep 0.1
done
