#!/usr/bin/env bash

startup() {
  echo "Started"
}

shutdown() {
  echo "Shutting down"
}

pause() {
  echo "Pause"
}

# $1 - Tag ID
on_tag() {
  echo "Scanned: '$1'"
}

# $1 - File path
playing_file() {
  echo "Playing file: '$1'"
}

# $1 - Volume
volume_changed() {
  echo "Volume changed: '$1'"
}