#!/usr/bin/env bash
# shellcheck disable=SC2034

music_dir="music"
start_volume="50"

pause_tag=""
shutdown_tag=""

volume_up_tag=""
volume_down_tag=""

seek_forward_tag=""
seek_backward_tag=""

next_tag=""
previous_tag=""

startup() {
  echo "Started"
}

shutdown() {
  echo "Shutting down"
}

pause() {
  echo "Pause"
}

# $1 - Tag ID
on_tag() {
  echo "Scanned: '$1'"
}

# $1 - File path
playing_file() {
  echo "Playing file: '$1'"
}

# $1 - Volume
volume_changed() {
  echo "Volume changed: '$1'"
}
