#!/usr/bin/env bash

log_file="$1"
[[ ! -f "$log_file" ]] && touch "$log_file"

# shellcheck source=jukebox-hooks
source "${2}"

trim_string() {
  echo "$1" | awk '{$1=$1};1'
}

get_timestamp() {
  date +%s%N | cut -b1-13
}

# Executes user hooks
#
# $1    - Hook name
# $2-$* - Hook arguments
hook() {
  hook_name="$1"
  shift
  if [[ "$(type -t "$hook_name")" == "function" ]]; then
    eval "$hook_name $*"
  fi
}

threshold=1000
unlocked() {
  if [[ -z $start_timestamp ]]; then
    start_timestamp=$(get_timestamp)
  else
    end_timestamp=$(get_timestamp)
    duration=$((end_timestamp - start_timestamp))
    if [[ "$duration" -lt "$threshold" ]]; then
      return 1
    fi
    start_timestamp=$(get_timestamp)
  fi
  return 0
}

tail -F "$log_file" | while read -r line; do
  line=$(echo "$line" | awk '{$1=$1};1')
  line=${line// :/:}

  filtered=$(echo "$line" | grep "ICY Info" | tail -1)
  if [[ -n "$filtered" ]]; then
    info=${filtered//ICY Info: StreamTitle=\'/}
    info=${info//\';/}
    info=${info//Gong 96.3 - Top50 - /}
  fi

  filtered=$(echo "$line" | grep "Title: " | tail -1)
  if [[ -n "$filtered" ]]; then
    title=${filtered//Title: /}
  fi

  filtered=$(echo "$line" | grep "Name: " | tail -1)
  if [[ -n "$filtered" ]]; then
    name=${filtered//Name: /}
  fi

  filtered=$(echo "$line" | grep "Artist: " | tail -1)
  if [[ -n "$filtered" ]]; then
    artist=${filtered//Artist: /}
  fi

  filtered=$(echo "$line" | grep "Year: " | tail -1)
  if [[ -n "$filtered" ]]; then
    year=${filtered//Year: /}
  fi

  filtered=$(echo "$line" | grep -v "http" | grep "Playing" | tail -1)
  if [[ -n "$filtered" ]]; then
    file=${filtered//Playing /}
    file=${file%?}
  fi

  if type "mp3info" >/dev/null; then
    [[ -f "$file" ]] && duration=$(mp3info "$file" -p "%m:%s")
  fi

  if [[ -n "$name" ]] && [[ -n "$info" ]]; then
    if unlocked; then
      hook "playing_stream" "${name@Q}" "${info@Q}"
    fi
    unset info
    continue
  fi

  if [[ -n "$artist" ]] && [[ -n "$title" ]] && [[ -n "$duration" ]] && [[ -n "$year" ]]; then
    if unlocked; then
      hook "playing_song" "${artist@Q}" "${title@Q}" "${year@Q}" "${duration@Q}"
    fi
    unset artist
    unset title
    unset duration
    unset year
    continue
  fi

done
