#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

mplayer_process="mplayer -slave"
control_pipe="/tmp/nfc-jukebox-pipe"
log_file="/tmp/nfc-jukebox-logfile.log"

# shellcheck source=nfc-jukebox-config
source "$script_dir""/nfc-jukebox-config"

volume=50
# shellcheck disable=SC2154
if [[ -n "$start_volume" ]]; then
  volume="$start_volume"
fi

# Get absolute path of directory
music_dir=$(readlink -f "$music_dir")
if [[ ! -d "$music_dir" ]]; then
  echo "Not a valid music directory: '$music_dir'"
  exit 1
fi

# Cleanup
teardown() {
  echo && hook "shutdown"
  kill_process "$mplayer_process"
}

# We want to cleanup, if the script gets killed.
trap teardown EXIT

# Executes user hooks
#
# $1    - Hook name
# $2-$* - Hook arguments
hook() {
  hook_name="$1"
  shift
  if [[ "$(type -t "$hook_name")" == "function" ]]; then
    eval "$hook_name $*"
  fi
}

# This file is used to control mplayer.
create_control_pipe() {
  [[ -p "$control_pipe" ]] && rm "$control_pipe"
  mkfifo "$control_pipe"
}

# Kills a process by its name.
#
# $1 - Process name
kill_process() {
  pids=$(pgrep -f "$1")
  if [[ -n "$pids" ]]; then
    for pid in $pids; do
      if [[ "$pid" != "$$" ]]; then
        echo "Stopping process: $pid"
        disown "$pid" >/dev/null 2>&1
        kill -9 "$pid"
      fi
    done
  fi
}

# The playback is stopped by killing mplayer.
stop_playback() {
  pids=$(pgrep -f "$mplayer_process")
  if [[ -n "$pids" ]]; then
    echo "quit" >"$control_pipe" &
    sleep 0.1
    kill_process "$mplayer_process"
  fi
}

start_playback() {
  stop_playback
  create_control_pipe

  file="$1"
  filename=$(basename -- "$file")
  extension="${filename##*.}"

  arguments=(
    "-slave"
    "-shuffle"
    "-volume" "$volume"
    "-msglevel" "all=4"
    "-loop" "0"
    "-input" "file=$control_pipe"
  )

  if [[ "$extension" == "txt" ]]; then
    # get random line from the file
    file="$(shuf -n 1 "$file")"
  fi

  if [[ "$file" == *.m3u ]]; then
    arguments=("${arguments[@]}" "-playlist" "$file")
  elif [[ -d "$file" ]]; then
    arguments=("${arguments[@]}" "$file/"*)
  else
    arguments=("${arguments[@]}" "$file")
  fi

  nohup mplayer "${arguments[@]/#/}" &>>"$log_file" &
}

# We have to remember the volume ourselves.
set_volume() {
  volume=$((volume + $1))

  if [[ "$volume" -gt 100 ]]; then
    volume=100
  fi

  if [[ "$volume" -lt 10 ]]; then
    volume=10
  fi

  hook "volume_changed" "$volume"
  echo "volume $volume 1" >"$control_pipe" &
}

# Returns a unix timestamp
get_timestamp() {
  date +%s%N | cut -b1-13
}

echo && hook "startup"

# Here the actual logic begins.
# The script waits for the input from the NFC scanner.
while true; do
  read -rep $'Waiting for tag...\n' tag_id

  if [[ -z "$tag_id" ]]; then
    continue
  fi

  # We want to avoid redundant scans.
  # Accordingly, a short timeout is inserted here.
  if [[ -z $start_timestamp ]]; then
    start_timestamp=$(get_timestamp)
  else
    end_timestamp=$(get_timestamp)
    if [[ "$((end_timestamp - start_timestamp))" -lt 500 ]]; then
      echo "Temporary locked"
      continue
    fi
    start_timestamp=$(get_timestamp)
  fi

  hook "on_tag" "$tag_id"

  # Searching for the file that starts with given tag_id
  entry=$(find "$music_dir" -name "$tag_id - *")

  if [[ -f "$entry" ]] || [[ -d "$entry" ]]; then
    hook "playing_file" "$(printf '%q\n' "$entry")"
    start_playback "$entry"
    continue
  fi

  # shellcheck disable=SC2154
  if [[ -n "$pause_tag" ]] && [[ "$tag_id" == "$pause_tag" ]]; then
    hook "pause"
    echo "pause" >"$control_pipe" &
    continue
  fi

  # shellcheck disable=SC2154
  if [[ -n "$seek_forward_tag" ]] && [[ "$tag_id" == "$seek_forward_tag" ]]; then
    echo "seek +15 0" >"$control_pipe" &
    continue
  fi

  # shellcheck disable=SC2154
  if [[ -n "$seek_backward_tag" ]] && [[ "$tag_id" == "$seek_backward_tag" ]]; then
    echo "seek -15 0" >"$control_pipe" &
    continue
  fi

  # shellcheck disable=SC2154
  if [[ -n "$volume_up_tag" ]] && [[ "$tag_id" == "$volume_up_tag" ]]; then
    set_volume 10
    continue
  fi

  # shellcheck disable=SC2154
  if [[ -n "$volume_down_tag" ]] && [[ "$tag_id" == "$volume_down_tag" ]]; then
    set_volume -10
    continue
  fi

  # shellcheck disable=SC2154
  if [[ -n "$next_tag" ]] && [[ "$tag_id" == "$next_tag" ]]; then
    echo "pt_step 1" >"$control_pipe" &
    continue
  fi

  # shellcheck disable=SC2154
  if [[ -n "$previous_tag" ]] && [[ "$tag_id" == "$previous_tag" ]]; then
    echo "pt_step -1" >"$control_pipe" &
    continue
  fi

  # shellcheck disable=SC2154
  if [[ -n "$shutdown_tag" ]] && [[ "$tag_id" == "$shutdown_tag" ]]; then
    echo "pause" >"$control_pipe" &
    break
  fi

done