#!/usr/bin/env bash

startup() {
  echo "Started"
  nohup mplayer -slave -volume 60 ../nfc-jukebox-resources/startup.m4a >/dev/null 2>&1 &
}

shutdown() {
  echo "Shutting down"
  nohup mplayer -slave -volume 60 ../nfc-jukebox-resources/shutdown.m4a >/dev/null 2>&1 &
}

pause() {
  echo "Pause"
}

# $1 - Tag ID
on_tag() {
  echo "Scanned: '$1'"
}

# $1 - File path
playing_file() {
  echo "Playing file: '$1'"
}

# $1 - Volume
volume_changed() {
  echo "Volume changed: '$1'"
}