#!/usr/bin/env bash

git clone https://github.com/kolbasa/nfc-jukebox --depth 1 "/home/pi/JukeBox"

autostart_dir="/home/pi/.config/lxsession/LXDE-pi/"
if [[ ! -d "$autostart_dir" ]]; then
  mkdir -p "$autostart_dir"
fi

autostart_file="$autostart_dir/autostart"

if [[ -f "$autostart_file" ]]; then
cat > "$autostart_file" << EOF
@lxpanel --profile LXDE-pi
@pcmanfm --desktop --profile LXDE-pi
@lxterminal -e "/home/pi/JukeBox/nfc-jukebox/nfc-jukebox/nfc-jukebox"
EOF
fi