#!/usr/bin/env bash

jukebox_dir="/home/pi/JukeBox"
if [[ ! -d "$jukebox_dir" ]]; then
  git clone https://github.com/kolbasa/nfc-jukebox --depth 1 "$jukebox_dir"
fi

autostart_dir="/home/pi/.config/lxsession/LXDE-pi/"
if [[ ! -d "$autostart_dir" ]]; then
  mkdir -p "$autostart_dir"
fi

autostart_file="$autostart_dir/autostart"
if [[ -f "$autostart_file" ]]; then
  rm "$autostart_file"
fi

cat >"$autostart_file" <<EOF
@lxpanel --profile LXDE-pi
@pcmanfm --desktop --profile LXDE-pi
@lxterminal --working-directory=/home/pi/JukeBox -e "./nfc-jukebox"
EOF
